server:
  port: 8080
  servlet:
    session:
      #timeout: 604800 #7天
      timeout: 31536000 #1年
      cookie:
        name: SESSION
        domain: null #改为域名后，只能在此域名有效
  tomcat:
    max-threads: 1000
    min-spare-threads: 200
    accept-count: 1000
    max-connections: 1000
 # connection-timeout: 60
spring:
  datasource:
    name: master
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/game_machine_db
    username: root
    password: liliu
    type: com.alibaba.druid.pool.DruidDataSource
    #初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    #配置获取连接等待超时的时间
    max-wait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  redis:
    host: 127.0.0.1
    password: liliu
    port: 6379
    database: 1
    timeout: 3000
    jedis:
      pool:
        min-idle: 100
        max-idle: 300
        max-active: 800
    lettuce:
      pool:
        min-idle: 100
        max-idle: 300
        max-active: 800
myPugin:
  jmx:
    rmi:
      hostname: 127.0.0.1
      port: 1234
  uploaderPath:
    rootPath: /home
    locationPath: /uploaderPath/img
  projectName: gameMachineProject
  projectDomainUrl: http://zbb.tea18.cn
  alibaba:
    sms:
      appkey: LTAI8pvFPmyGx9Kg
      appsecret: SyMF4xGS3WXJP5uNxr4rU6r91DrQy5
      signName: 欢乐抓包包
      templateCodeAcountRegister: SMS_158036761
      templateCodePasswordUpdate: SMS_158051607
      templateCodeWithdrawalsPasswordUpdate: SMS_158051607
      templateCodePhoneUpdate: SMS_158051607
      templateCodeAuthenticationBind: SMS_158051607
  weixin:
    mp:
      #微信公众号或者小程序等的appid
      appId: wx4d2cb896c1256cbe
      #微信公众号或者小程序等的secret
      secret: fc1eeae1ae1c69caa68d87d5e55f7659
    pay:
      #微信公众号或者小程序等的appid
      appId: wx4d2cb896c1256cbe
      #微信支付商户号
      mchId: 1513989441
      #微信支付商户密钥
      mchKey: zk0yd2n2e4velz2afqnyiknbnburrjdh
      #服务商模式下的子商户公众账号ID
      subAppId:
      #服务商模式下的子商户号
      subMchId:
      # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
      keyPath:
  shiro:
    anon:
      locations: /** , /*.txt  , /swagger-resources/** , /swagger-ui.html , /webjars/** , /v2/** , /home/** , /resources/** , /uploaderPath/** , /weixin/**, /wechat/**